services:
  - type: web
    name: techmitra-backend
    rootDir: backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    pythonVersion: 3.12
